# Copyright (c) 2020 Ryan Cross
# SPDX-License-Identifier: MIT 

# Enable the Sofle OLED Display
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y

# Custom OLED Animation Widgets (Bongo Cat on Left / Central, Luna on Right / Peripheral)
CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS_BONGO_CAT=y
CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS_LUNA=y
CONFIG_NICE_OLED_WPM_DISPLAY=4

# Support for encoders
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Set sleep timeout to 10min (10*60*1000ms)
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=600000
CONFIG_ZMK_IDLE_TIMEOUT=30000


